#pragma once

/// @cond internal
enum
{
    ZIP64_HEADER = 0x0001,
    NTFS_HEADER = 0x000A,
    NTFS_FILE_TIME_TAG = 0x0001,
    UNIX_HEADER = 0x000D,
    UNIX_EXTENDED_TIMESTAMP_HEADER = 0x5455,
    INFO_ZIP_UNIX_HEADER = 0x5855,
    INFO_ZIP_UNICODE_PATH_HEADER = 0x7075,
    INFO_ZIP_UNICODE_COMMENT_HEADER = 0x6375,
    WINZIP_EXTRA_FIELD_HEADER = 0x5A4C,

    UNIX_MOD_TIME_FLAG = 1 << 0,
    UNIX_ACC_TIME_FLAG = 1 << 1,
    UNIX_CRT_TIME_FLAG = 1 << 2,
    WINZIP_FILENAME_CODEPAGE_FLAG = 1 << 0,
    WINZIP_ENCODED_FILENAME_FLAG = 1 << 1,
    WINZIP_COMMENT_CODEPAGE_FLAG = 1 << 2,
};
/// @endcond
